export const BARANGAY_DATA: Record<string, string[]> = {
  "District 1": ["Alicia", "Bagong Pag-asa", "Bahay Toro", "Balingasa", "Bungad", "Damar", "Damayan", "Del Monte", "Katipunan", "Lourdes", "Maharlika", "Manresa", "Mariblo", "Masambong", "Nayong Kanluran", "Paang Bundok", "Pag-ibig sa Nayon", "Paltok", "Paraiso", "Phil-Am", "Project 6", "Quirino 2-A", "Quirino 2-B", "Ramon Magsaysay", "Salvacion", "San Antonio", "San Isidro Labrador", "San Jose", "Siena", "St. Peter", "Sta. Lucia", "Sta. Cruz", "Sta. Teresita", "Sto. Cristo", "Sto. Domingo", "Sto. Niño", "Talayan", "Vasra", "Veterans Village", "West Triangle"],
  "District 2": ["Bagong Silangan", "Batasan Hills", "Commonwealth", "Holy Spirit", "Payatas"],
  "District 3": ["Amihan", "Bagumbayan", "Blue Ridge A", "Blue Ridge B", "Camp Aguinaldo", "Dioquino Zobel", "Don Manuel", "Duyan-Duyan", "E. Rodriguez", "East Kamias", "Escopa 1", "Escopa 2", "Escopa 3", "Escopa 4", "Libis", "Loyola Heights", "Mangga", "Marilag", "Masagana", "Matandang Balara", "Milagrosa", "N.S. Amoranto", "Pansol", "Quirino 2C", "Quirino 3A", "Quirino 3B", "Silangan", "Socorro", "St. Ignatius", "Tagumpay", "Ugong Norte", "Villa Maria Clara", "West Kamias", "White Plains"],
  "District 4": ["Bagong Lipunan ng Crame", "Botocan", "Central", "Damayang Lagi", "Doña Aurora", "Doña Imelda", "Doña Josefa", "Horseshoe", "Immaculate Concepcion", "Kamuning", "Kalusugan", "Kaunlaran", "Kristong Hari", "Krus na Ligas", "Laging Handa", "Malaya", "Mariana", "Obrero", "Old Capitol Site", "Paligsahan", "Pinagkaisahan", "Pinyahan", "Roxas", "Sacred Heart", "San Isidro Galas", "San Martin de Porres", "San Roque", "San Vicente", "Santol", "Sikatuna Village", "South Triangle", "Tatalon", "Teachers Village East", "Teachers Village West", "Valencia"],
  "District 5": ["Bagbag", "Capri", "Fairview", "Greater Lagro", "Gulod", "Kaligayahan", "Nagkaisang Nayon", "North Fairview", "Novaliches Proper", "Pasong Putik", "San Agustin", "San Bartolome", "Sta. Monica"],
  "District 6": ["Apolonio Samson", "Baesa", "Balong-Bato", "Culiat", "New Era", "Pasong Tamo", "Sangandaan", "Sauyo", "Talipapa", "Tandang Sora", "Unang Sigaw", "UP Campus", "UP Village"]
};

export const EVACUATION_DATA: Record<string, string[]> = {
  "Alicia": ["Brgy Alicia Hall – 3rd Floor", "Bago Bantay Elementary School"],
  "Bagong Pag-asa": ["Open Ground", "Bagong Pag-asa Elementary School", "Multipurpose Covered Court"],
  "Bahay Toro": ["Bahay Toro Basketball Court", "Basketball Court", "Toro Hills Elementary School"],
  "Balingasa": ["Barangay Hall Covered Court"],
  "Bungad": ["Barangay Bungad Covered Court", "Bungad Elementary School"],
  "Damar": ["Basketball Covered Court", "Multi-Purpose Hall", "Function Room"],
  "Damayan": ["Cong Calalay Elementary School", "Minor Basilica of Saint Pedro Bautista"],
  "Del Monte": ["Dalupan Elementary School", "San Francisco Elementary School"],
  "Katipunan": ["San Antonio Elementary School", "Basketball Covered Court"],
  "Lourdes": ["Basketball Covered Court"],
  "Maharlika": ["PureGold Kanlaon", "National Shrine of Our Lady of Lourdes"],
  "Manresa": ["Basketball Covered Court", "Playground"],
  "Mariblo": ["Barangay Hall (Mariblo)", "Day Care Center"],
  "Masambong": ["Tennis Court", "Gazebo Hall", "Parking Space"],
  "Nayong Kanluran": ["Nayong Kanluran Barangay Hall", "Nayong Kanluran Covered Court"],
  "Paang Bundok": ["Barangay Hall Paang Bundok", "Open Space"],
  "Pag-ibig sa Nayon": ["Barangay Covered Court", "Yakap Day Care Center", "San Jose Elementary School"],
  "Paltok": ["Paltok Covered Court", "Paltok Elementary School", "Bayanihan Elementary School", "Paltok Barangay Hall"],
  "Paraiso": ["Residential House"],
  "Phil-Am": ["Phil-Am Football Field"],
  "Project 6": ["Veterans Covered Court", "Project 6 Elementary School", "Project 6 Park", "Multipurpose Hall – 3rd Floor"],
  "Quirino 2-A": ["Quirino 2A Multipurpose Hall"],
  "Quirino 2-B": ["Quirino High School & Elementary School", "Barangay Hall & Covered Court"],
  "Ramon Magsaysay": ["Parking Space & 3rd Floor of Brgy", "Covered Court"],
  "Salvacion": ["Salvacion Barangay Hall"],
  "San Antonio": ["San Antonio De Padua Parish Church", "San Jose Covered Court"],
  "San Isidro Labrador": ["San Isidro Labrador Barangay Hall"],
  "San Jose": ["San Jose Elementary School", "Basketball Covered Court"],
  "Siena": ["Siena Barangay Hall (4th Floor)", "Siena College of Quezon City (Open Space)"],
  "St. Peter": ["Barangay Multipurpose Hall"],
  "Sta. Lucia": ["Sta. Lucia Multipurpose Building", "Sta. Lucia Covered Court"],
  "Sta. Cruz": ["Barangay Multipurpose Hall", "Day Care Center (3rd Floor)"],
  "Sta. Teresita": ["Sta. Teresita Covered Court"],
  "Sto. Cristo": ["Sto. Cristo Elementary School"],
  "Sto. Domingo": ["The Santo Domingo Church and Convent"],
  "Sto. Niño": ["Sto. Niño Barangay Hall"],
  "Talayan": ["Talayan Village Park"],
  "Vasra": ["Barangay Hall (3rd Floor)", "VMMC Hospital Open Space"],
  "Veterans Village": ["Esteban Abada Elementary School", "Lucrecia Kasilag High School", "Covered Court"],
  "West Triangle": ["Barangay Hall Multipurpose Hall", "Basketball Covered Court", "Open Space (JASMS compound)"],
  "Bagong Silangan": ["Evacuation Site", "Bagong Silangan Elementary School", "Bagong Silangan High School", "Bona Multipurpose Hall", "Brookside Evacuation Site", "Clemencia Evacuation Center", "Fil-Heights Club House", "Humanity Ville Evacuation Center", "Kawan Chapel", "Lumang Palengke", "Pocalari Evacuation Center", "San Isidro Church", "Scandinavian School Area 6"],
  "Batasan Hills": ["Area A-3 Covered Court", "Saret Covered Court", "Freedom Park Covered Court", "Batasan National High School", "San Diego Elementary School", "President Corazon Aquino Elementary School", "Phase I Covered Court"],
  "Commonwealth": ["BYC Covered Court", "Soliven Covered Court", "Kaunlaran Covered Court", "MRB Covered Court"],
  "Holy Spirit": ["Covered Court", "Gilarmi Covered Court", "Sto. Niño Covered Court", "LRB Covered Court"],
  "Payatas": ["Multi-Purpose Hall", "Payatas Phase 2 Covered Court", "Payatas Phase 4 Covered Court", "Golden Shower Covered Court", "Plaza Dos Covered Court", "Bulacan St. Barangay Hall Covered Court", "Payatas Livelihood Building", "Talisay Covered Court"],
  "Amihan": ["Open Space", "Quirino High School"],
  "Bagumbayan": ["Mangahan Fire Station – 2nd Floor", "Multipurpose Sr. Hall", "Bagumbayan Elementary School", "Covered Court", "Kalantiaw Elementary School"],
  "Blue Ridge A": ["Tennis Court & Basketball Court", "Parking Area in front of Barangay Hall"],
  "Blue Ridge B": ["Barangay Hall"],
  "Camp Aguinaldo": ["Open Space"],
  "Duyan-Duyan": ["Covered Court", "Project 3 Elementary School", "High School"],
  "E. Rodriguez": ["Carlos P. Garcia High School", "E. Rodriguez Elementary School", "Nativity of the Lord Parish Church", "Cubao Elementary School"],
  "East Kamias": ["Barangay Hall – 2nd & 3rd Floor", "Multipurpose Hall", "Open Space"],
  "Escopa 1": ["Mini Plaza"],
  "Escopa 2": ["Katipunan Avenue near QMMC"],
  "Escopa 3": ["NVRC"],
  "Escopa 4": ["Escopa 4 Multipurpose Hall"],
  "Libis": ["Multi-Purpose Hall Covered Court", "Open Space"],
  "Loyola Heights": ["Covered Court", "Multipurpose Hall"],
  "Marilag": ["3rd Floor Barangay Hall & Event Place", "National College of Business and Arts", "T. Alonzo Elementary School"],
  "Masagana": ["MTD & SB Building", "Covered Court", "Paciano Rizal Oval", "Open Space"],
  "Matandang Balara": ["Old Balara Elementary School", "Tandang Sora Covered Court"],
  "Milagrosa": ["5K Open Space"],
  "N.S. Amoranto": ["E. Rodriguez Elementary School", "Tennis Court", "Basketball Court"],
  "Pansol": ["Balara Elementary School", "Balara High School", "Kaingin I Covered Court", "Kaingin II Covered Court"],
  "Quirino 3A": ["Quirino 3A Barangay Hall", "Open Space"],
  "Silangan": ["Silangan Barangay Hall", "Friendship Covered Court"],
  "Socorro": ["Camp Aguinaldo", "15th Elementary School Basketball Covered Court", "SM Cubao Parking"],
  "St. Ignatius": ["St. Ignatius Open Space"],
  "Tagumpay": ["Open Space"],
  "Ugong Norte": ["Barangay Hall", "Corinthian Garden Clubhouse", "Arcadia Clubhouse", "Open Space"],
  "Villa Maria Clara": ["Open Space", "Pelaez Park"],
  "West Kamias": ["Multipurpose Hall"],
  "White Plains": ["Tennis Court", "Basketball Court"],
  "Bagong Lipunan ng Crame": ["Open Court", "Open Space"],
  "Botocan": ["Botocan Barangay Hall – 3rd Floor", "Suntay Multipurpose Building"],
  "Central": ["Quezon Memorial Circle", "Kalayaan Service Road", "Suntay Multipurpose Building", "Daza Hall", "Orchids Covered Court"],
  "Damayang Lagi": ["TUA Building", "San Lorenzo"],
  "Doña Aurora": ["Jacinto Basketball Covered Court", "Barangay Hall", "Our Lady of Sacred Heart School"],
  "Doña Imelda": ["Multipurpose Hall Gymnasium", "Malangen Hall", "Suntay Amphitheater", "Justice Hall"],
  "Kamuning": ["Barangay Function Hall", "KD Covered Court", "Senior Building Hall", "Vicente Hall", "Suntay Multipurpose Hall"],
  "Kalusugan": ["Kalusugan Barangay Hall", "Multipurpose Building"],
  "Kristong Hari": ["Marvin Rillo Multipurpose", "Aray Building", "Lagman Building"],
  "Krus na Ligas": ["Baluyot Covered Court", "Baluyot Multipurpose Building"],
  "Malaya": ["Basketball Covered Court", "Malaya Elementary School"],
  "Mariana": ["National Shrine of Our Lady of Mt. Carmel"],
  "Obrero": ["Don Alejandro Roces Sr. High School", "Old Barangay Building"],
  "Old Capitol Site": ["Basketball Covered Court", "Open Space", "Barangay Hall Annex"],
  "Roxas": ["Roxas Multipurpose Gymnasium", "Roxas Covered Court", "Holy Family Parish Church"],
  "Sacred Heart": ["Kamuning Elementary School", "Sacred Heart Parish – Shrine"],
  "San Roque": ["Aguinaldo Elementary School Covered Court", "San Roque Barangay Hall (3rd Floor)"],
  "Sikatuna Village": ["1st Quadrant", "2nd Quadrant", "3rd Quadrant", "4th Quadrant"],
  "South Triangle": ["South Triangle Barangay Hall"],
  "Tatalon": ["Mabuhay Court", "Diosdado Macapagal Elementary School Covered Court"],
  "Teachers Village East": ["Teachers Village East Barangay Hall", "C.P. Garcia Park"],
  "Teachers Village West": ["Claret School of Quezon City"],
  "Valencia": ["Valencia Barangay Hall", "SK Hall", "Open Court"],
  "Bagbag": ["San Pedro Covered Court", "SB Park Covered Court", "St. Nicholas of Bari School", "Remarville Covered Court"],
  "Capri": ["Capri Activity Center", "Covered Court"],
  "Fairview": ["Fairlane Elementary School", "The Church of Jesus Christ", "Sitio Sto. Niño"],
  "Greater Lagro": ["A. Centennial Park Dulo", "B Plaza Gitna", "C. Mindanao Ave. Ext Open Space", "Fatima University Covered Court"],
  "Gulod": ["Elementary School"],
  "Kaligayahan": ["Zabarte Covered Court", "Multipurpose Hall", "Roxas Vargas Hall"],
  "Nagkaisang Nayon": ["Banahaw St. Open Space", "Pasacola Area D Basketball Covered Court", "Goldmine Basketball Court", "Robina Covered Court"],
  "North Fairview": ["North Fairview Basketball Court"],
  "Novaliches Proper": ["Barangay Hall – 3rd Floor", "Vargas Building", "Dona Isaura Covered Court", "Dona Rosario Covered Court / Command Center", "SB Plaza"],
  "Pasong Putik": ["Feliciano Covered Court", "Celpito Covered Court", "Petchayang Covered Court"],
  "San Agustin": ["Vargas Multi-Purpose Hall", "T.S Park"],
  "San Bartolome": ["California Village", "Nomar II Covered Court", "Odelco Covered Court", "Odelco Elementary School"],
  "Sta. Monica": ["Villaverde Covered Court", "Santiago Subd Covered Court", "Lydia Covered Court", "Palmera Phase II Covered Court", "Palmera Phase IV Covered Court"],
  "Apolonio Samson": ["Apolonio Samson Elementary School"],
  "Baesa": ["Covered Court Asamba", "Monotoc Covered Court", "Elementary School", "Saint Martin De Porres Chapel", "Dead End Court"],
  "Balong-Bato": ["Balon-Bato Health Center", "Balon-Bato Elementary School"],
  "Culiat": ["Vargas Compound Covered Court", "Multipurpose Hall", "Culiat High School", "Salam Covered Court", "Bernardo Covered Court Multi-Purpose Hall", "Pael Multipurpose Hall"],
  "New Era": ["Disaster Building", "MRF Building"],
  "Pasong Tamo": ["Marcel Village Covered Court", "Veteran Annex I", "Pingkian / Central Annex II", "Pantranco Chapel"],
  "Sangandaan": ["Mendoza Multipurpose Building – 3rd Floor", "Mathay High School"],
  "Sauyo": ["Sotto Multipurpose Building", "Sauyo Elementary School", "Del Nacia Ville Covered Court", "NIA Covered Court", "Sauyo Covered Court"],
  "Talipapa": ["Talipapa Barangay Hall – 3rd Floor", "Placido del Mundo Elementary School", "Villa Sabina Park", "Volleyball Court", "Silvina Village Sports Complex", "Sahara Sports Complex Basketball Court"],
  "Tandang Sora": ["Tandang Sora Barangay Hall", "Tandang Sora Covered Court"],
  "Unang Sigaw": ["Covered Court (Camachile Police Station 3 QCPD)"],
  "UP Campus": ["Amorsolo Building", "Village B Covered Court", "Dagohoy Hall"],
  "UP Village": ["Basketball Court", "Tennis Court"]
};
